"""Add print_areas to Product model

Revision ID: 03b8bad9d7bc
Revises: 15219f464205
Create Date: 2025-08-30 13:54:31.922067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b8bad9d7bc'
down_revision = '15219f464205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('print_areas', sa.JSON(), nullable=True))
        batch_op.drop_column('editor_template_url_front')
        batch_op.drop_column('editor_template_url_back')
        batch_op.drop_column('printful_product_id')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('printful_product_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('editor_template_url_back', sa.VARCHAR(length=512), nullable=True))
        batch_op.add_column(sa.Column('editor_template_url_front', sa.VARCHAR(length=512), nullable=True))
        batch_op.drop_column('print_areas')

    # ### end Alembic commands ###
