"""Initial migration from existing database structure

Revision ID: 17b27253d2c2
Revises: 
Create Date: 2025-09-09 22:03:17.278776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b27253d2c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_urls', sa.JSON(), nullable=True))
        batch_op.drop_column('preview_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('preview_urls')

    # ### end Alembic commands ###
