"""Add manual_print_areas to Product

Revision ID: 1a6f35dd8bec
Revises: phase3_001
Create Date: 2026-06-22 12:43:55.288213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6f35dd8bec'
down_revision = 'phase3_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_print_areas', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('manual_print_areas')

    # ### end Alembic commands ###
