"""Add is_admin to User model

Revision ID: 36410dbc8fd4
Revises: 5d7e1850b64e
Create Date: 2025-09-05 22:19:38.234135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36410dbc8fd4'
down_revision = '5d7e1850b64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
