"""Add merch_color_type to product

Revision ID: 3702abdc069f
Revises: d52d4325efb5
Create Date: 2025-09-02 22:08:34.435417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3702abdc069f'
down_revision = 'd52d4325efb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merch_color_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.drop_column('merch_color_type')

    # ### end Alembic commands ###
