"""Move merch_color_type to Product table

Revision ID: 55aa12ecb250
Revises: b955ba12bce6
Create Date: 2025-09-02 23:05:29.921856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55aa12ecb250'
down_revision = 'b955ba12bce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.drop_column('merch_color_type')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merch_color_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('merch_color_type')

    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merch_color_type', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
