"""Add printful_variant_id to Product

Revision ID: 58afd2a2c0e4
Revises: 03b8bad9d7bc
Create Date: 2025-08-30 18:23:36.471370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58afd2a2c0e4'
down_revision = '03b8bad9d7bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('printful_variant_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('printful_variant_id')

    # ### end Alembic commands ###
