"""Create product and variant tables

Revision ID: 7abc2912c323
Revises: 4acf1adca603
Create Date: 2025-09-04 20:47:47.880071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7abc2912c323'
down_revision = '4acf1adca603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('printful_variant_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('merch_color_type', sa.String(length=10), nullable=False),
    sa.Column('print_areas', sa.JSON(), nullable=False),
    sa.Column('available_regions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('printful_variant_id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('printful_product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint("uq_product_printful_product_id", ['printful_product_id'])
        batch_op.drop_column('print_areas')
        batch_op.drop_column('merch_color_type')
        batch_op.drop_column('price')
        batch_op.drop_column('printful_variant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('printful_variant_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('merch_color_type', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('print_areas', sqlite.JSON(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('printful_product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('variant')
    # ### end Alembic commands ###
