"""Add Prinftul order tracking to Order model

Revision ID: 91e39dcea51e
Revises: 55aa12ecb250
Create Date: 2025-09-03 17:19:17.948389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e39dcea51e'
down_revision = '55aa12ecb250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('printful_order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('printful_order_status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('printful_order_status')
        batch_op.drop_column('printful_order_id')

    # ### end Alembic commands ###
