"""Add variant_id to Design model

Revision ID: 9381596881c0
Revises: 58afd2a2c0e4
Create Date: 2025-08-30 19:25:33.354193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9381596881c0'
down_revision = '58afd2a2c0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.drop_column('variant_id')

    # ### end Alembic commands ###
