"""Add Stripe and Printful tracking to Order

Revision ID: 9f93ed0e6106
Revises: 91e39dcea51e
Create Date: 2025-09-03 18:34:55.545338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f93ed0e6106'
down_revision = '91e39dcea51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_session_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['stripe_session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stripe_session_id')

    # ### end Alembic commands ###
