"""Add Printful colums to Product model

Revision ID: d52d4325efb5
Revises: fe615766f393
Create Date: 2025-08-31 14:34:08.214267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52d4325efb5'
down_revision = 'fe615766f393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('printful_product_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('printful_product_id')

    # ### end Alembic commands ###
