"""Add preview_url to Design model

Revision ID: fe615766f393
Revises: 9381596881c0
Create Date: 2025-08-30 19:40:38.476397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe615766f393'
down_revision = '9381596881c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
        batch_op.drop_column('preview_url')

    # ### end Alembic commands ###
